#!/bin/bash
if [ $# -eq 0 ]; then
  command=$(cat "$HOME/.bash_history" | fzf)
else
  command=$(cat "$HOME/.bash_history" | fzf --query="$@")
fi

if [ "$command" = "" ]; then
  exit
fi

if [ "$command" = "cancel" ]; then
  exit
fi

read -e -i "$command" -p "Execute command: " command

echo "$command" >> "$HOME/.bash_history"
eval "$command"
